### PR TITLE
added subtype_013; same as for type_013 but for subtype

### LINKED ISSUE #1003: Add case rules for subtype declarations.
The `subtype` and `is` keywords do not have case rules.

### PR DESCRIPTION
**Pull request by zack-vii**
**Description**
Added rule 013 case check if is keyword analogue to rule 013 of type.

**Screenshots**
none

**Additional context**
adds probably forgotten rule.

Resolves #1003

### CODE REVIEW

**Review by jeremiah-c-leary — CHANGES_REQUESTED** [review]
Hey @zack-vii,

I have started a new numbering convention and was wondering if you could change rule_013 to rule_501?

**Comment by zack-vii** [comment]
Hi @jeremiah-c-leary , I rebased the branch on current master and wanted to get a clean copy of type's rule_501 but it seem rule 501 is "This rule checks for consistent capitalization of enumerated types.". Are you sure about the code or maybe your changes have not yet been checked it? I do not need credit for this so if it is easier, you can simply copy this and maybe other applicable rules form type_definition over as you go along.

**Comment by jeremiah-c-leary** [comment]
Morning @zack-vii ,

> I do not need credit for this so if it is easier, you can simply copy this and maybe other applicable rules form type_definition over as you go along

If you don't mind, I will create an issue and add two case rules:  one for the `subtype` keyword and another for the `is` keyword.

--Jeremy

**Comment by jeremiah-c-leary** [comment]
Morning @zack-vii,

I pushed an update to the issue-1003 branch.  I added three case rules:
* subtype_500 - checks case of `subtype` keyword
* subtype_501 - checks case of identifier
* subtype_502 - checks case of `is` keyword

Could you give it a try and let me know what you think.

Thanks,

--Jeremy

**Comment by zack-vii** [comment]
seems to work as expected. however i encountered an unrelated issue that can be fixed by initializing a variable.

I fixed it for me with this commit: fallback for dExpectedIndent in multiline_alignment_between_tokens

```diff
diff --git a/vsg/rules/multiline_alignment_between_tokens.py b/vsg/rules/multiline_alignment_between_tokens.py
index 7b5ac6fc8..f2e667fde 100644
--- a/vsg/rules/multiline_alignment_between_tokens.py
+++ b/vsg/rules/multiline_alignment_between_tokens.py
@@ -127,6 +127,7 @@ class multiline_alignment_between_tokens(alignment.Rule):
 
             iFirstTokenLength = len(lTokens[0].get_value())
 
+            dExpectedIndent = dActualIndent
             if self.align_paren == 'no' and self.align_left == 'yes':
                 dExpectedIndent = _analyze_align_left_yes_align_paren_no(iFirstLine, iLastLine, lParens, self.indentSize, dActualIndent, bStartsWithParen, self.bIgnoreStartParen, self.override)
             if self.align_paren == 'yes' and self.align_left == 'no':
```

**Comment by jeremiah-c-leary** [comment]
Evening @zack-vii ,

For the unrelated issue, could you create an issue with a code snippet example.  I would like to update my test suite to detect the issue so I can ensure it never comes back.

Thanks,

--Jeremy

**Comment by zack-vii** [comment]
created issue #1009 . Issue only occurs if the configuration is such that is does not hit any of the conditions in multiline_alignment_between_tokens

**Comment by jeremiah-c-leary** [comment]
Evening @zack-vii ,

I am going to assume I can close this pull request.  If you believe there is still work please re-open it.

Regards,

--Jeremy

**Pull request closed without merging**
