### PR TITLE
Extract type bug fix.

### PR DESCRIPTION
**Pull request by m-kru**
**Description**
State a clear description of the problem and your solution.

**Screenshots**
If applicable, add screenshots to help explain your solution.

**Additional context**
Add any other context about the problem here including related issue numbers.

### CODE REVIEW

**Comment by jeremiah-c-leary** [comment]
Hey m-kru,

I suspect the import change is causing Travis CI to fail.  I will have to look into this before I can merge the pull request.

**Comment by m-kru** [comment]
OK, import line does not work on my machine. I guess you did not want to import PyPI line, but line file from vsg.

**Comment by jeremiah-c-leary** [comment]
Interesting...I will investigate.

**Comment by jeremiah-c-leary** [comment]
I do not understand why there is a difference, but we can resolve it with the following change:

```python
try:
    from vsg import line
except ImportError:
    import line
```

**Pull request merged**
