### PR TITLE
Updates for issue #290:

### PR DESCRIPTION
**Pull request by jeremiah-c-leary**
Initial implementation of analysis portion of rule signal_017:

  1)  Added documentation
  2)  Added test
  3)  Added analysis portion of rule signal_017

@m-kru ,
This is the analysis portion of a rule to address issue #290.  Let me know what you think and we can talk about how to do the fix.

### CODE REVIEW

**Comment by m-kru** [comment]
@jeremiah-c-leary does the new rule 017 conflict with any other rules? By conflict I mean, if there are any 2 rules, that when enabled together lead to contradiction.

**Comment by jeremiah-c-leary** [comment]
rules `signal_015` and `signal_016` would conflict.  I was planning on making rule `signal_017` a superset of those rules and then depricate `signal_015` and `signal_016`.  Essentially, there would be a single rule to handle formatting of signal declarations.

There is still a lot of work to be done for `signal_017`, but I was wondering if this is what you are looking for.  Then I was going to  work on consolidating the other rules into `signal_017`.

**Comment by m-kru** [comment]
From user perspective, this is what I was looking for. Note that the are more classes where such rule could be applied. Namely `constant`, `variable`, `file`. I think it would be good idea to create some base class.

**Comment by jeremiah-c-leary** [comment]
hmm...you are probably correct about creating a base clase.  At the moment I want to get this rule working and then I will refactor it into a base clase.

**Comment by jeremiah-c-leary** [comment]
Hey @m-kru ,

I am going to close this pull request.  This implementation is now longer relevant with the parser re-write.

Hope things are going well for you.

--Jeremy

**Pull request closed without merging**
