### PR TITLE
docs: update installation methods

### PR DESCRIPTION
**Pull request by alonbl**
build system was modified to tox, documentation should have been updated.

### CODE REVIEW

**Comment by alonbl** [comment]
@jeremiah-c-leary there is a strange underline in GitHub rendering, from Installation and on, I could not find why, even before the place I touched.

**Comment by jeremiah-c-leary** [comment]
Evening @alonbl ,

Is there a reason a user would install `tox` if they did not want to do any development?  There is a section of the documentation where installing `tox` could be added.

You can see the gyrations I went through in my release process.  You're method is a lot cleaner.  Thank you.

--Jeremy

**Comment by alonbl** [comment]
> Is there a reason a user would install `tox` if they did not want to do any development? There is a section of the documentation where installing `tox` could be added.

As you provide the `bin` directory, users may checkout and use the tool directly as you intended.
But why will they want to use the master if they are not developing?
My intention was to remove all leftovers of the old build system which I have missed, feel free to modify in any way you like, I do not understand what section of documentation you refer to.

**Comment by jeremiah-c-leary** [comment]
Evening @alonbl ,

> But why will they want to use the master if they are not developing?

That is a good point.

> My intention was to remove all leftovers of the old build system which I have missed, feel free to modify in any way you like, I do not understand what section of documentation you refer to.

I already have a issue to update the development section, so I will make any necessary changes there.

I will merge this to master.

--Jeremy

**Pull request merged**
